### ISSUE TITLE
Received Error:400 - Invalid redirect_uri after lauching the apps

### ISSUE THREAD

**Issue by mpilouk** [Developer-Autodesk/data.management-csharp-a360sync#1]
I pulled this repo on to my local machine, modified the ServerOAuth Web.Config and added my Forge ClientId and ClientSecrete
    <add key="FORGE_CLIENT_ID" value="" />
    <add key="FORGE_CLIENT_SECRET" value="" />

I rebuilt the solution and modified the solution properties to use multiple startup projects as shown in the video. After launching the apps, I received the Error 400. I tried this on two laptops (Wiindows 10) and they showed the same error.

What am I missing?

**Comment by mpilouk** [comment]
I figured this out. Need to set the FAKE_CALLBACK_URL in the Config.cs and the FORGE_CALLBACK_URL in the Web.Config to be the value entered in callback URL of the created application on the https://developer.autodesk.com/myapps page.

**Comment by augustogoncalves** [comment]
that's right, I'll improve the readme :-) 

update: in fact this info was there, but due a formatting error (on my side), the readme was not showing it... sorry, fixed now.

**Comment by mpilouk** [comment]
Yeah, I reread it before you made the change and it was there, but wasn't obvious. The change looks good. Thanks.
